# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CorrectingOfDEM
                                 A QGIS plugin
 fiil the voids of your DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-12-17
        copyright            : (C) 2018 by vera_blinova
        email                : vera.blinova@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CorrectingOfDEM class from file CorrectingOfDEM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .correct_of_DEM import CorrectingOfDEM
    return CorrectingOfDEM(iface)
