# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CorrectingOfDEM
                                 A QGIS plugin
 fiil the voids of your DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-12-17
        git sha              : $Format:%H$
        copyright            : (C) 2018 by vera_blinova
        email                : vera.blinova@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
#from processing.core.Processing import Processing
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction,  QFileDialog, QLineEdit
from qgis.core import *
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .correct_of_DEM_dialog import CorrectingOfDEMDialog
import os.path


class CorrectingOfDEM:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CorrectingOfDEM_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = CorrectingOfDEMDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&correctingofDem')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'CorrectingOfDEM')
        self.toolbar.setObjectName(u'CorrectingOfDEM')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CorrectingOfDEM', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/correct_of_DEM/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Correct of DEM'),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&correctingofDem'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    
    def run(self):
        """Run method that performs all the real work"""

        self.dlg.cbox_dem_nodata.clear()
        self.dlg.cbox_dem_health.clear()
        self.dlg.cbox_nodata_shape.clear()
        # list of DEM
        layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        layer_dem_nodata_list = []
        layer_dem_health_list = []
        layer_nodata_shape_list = []
        
        for layer in layers:
            if isinstance(layer, QgsRasterLayer):
                layer_dem_nodata_list.append(layer.name())
            elif isinstance(layer, QgsVectorLayer):
                layer_nodata_shape_list.append(layer.name())
        self.dlg.cbox_dem_nodata.addItems(layer_dem_nodata_list)
        self.dlg.cbox_dem_health.addItems(layer_dem_nodata_list) # поменяй на layer_dem_health_list
        self.dlg.cbox_nodata_shape.addItems(layer_nodata_shape_list)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            if self.dlg.cbox_dem_nodata.currentIndex()==0 or self.dlg.cbox_dem_health.currentIndex()==0 or self.dlg.cbox_nodata_shape.currentIndex()==0:
                # вывести ошибку так как все поля должны быть не пустыми
                pass
            # получение данных
            for layer in layers:
                if (self.dlg.cbox_dem_nodata.currentText() == layer.name()):
                    dem_nodata = layer
                elif (self.dlg.cbox_dem_health.currentText() == layer.name()):
                    dem_health = layer
                elif (self.dlg.cbox_nodata_shape.currentText() == layer.name()):
                    shape_nodata = layer

            higths = dem_nodata.constDataProvider().identify(QgsPointXY(-593779.9,2956635.4),1).results()
            provider = shape_nodata.dataProvider()
            feat = QgsFeature()
            iterator = provider.getFeatures()
            print(shape_nodata.LayerConfiguration)
#            while iterator.nextFeature(feat):
#                current_hole = QgsVectorLayer("Polygon","cur_h","memory")
#                pr = current_hole.dataProvider()
#                pr.addAttributes([QgsField("Parts", QVariant.String),
#                                  QgsField("Length", QVariant.Double),
#                                  QgsField("Area", QVariant.Double),
#                                  QgsField("Type", QVariant.Int)])
#                pr.addFeature(feat)
                

            
#            allAttrs = provider.attributeIndexes()
#            print(allAttrs)






